# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GZH_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_id', models.CharField(max_length=30, unique=True)),
                ('gzh_head_pic', models.URLField()),
                ('fun_info', models.CharField(max_length=200)),
                ('wcrz', models.CharField(max_length=100)),
                ('gzh_paper_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GZH_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
