# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_gzh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gzh_info',
            name='gzh_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat_gzh.GZH_list'),
            preserve_default=False,
        ),
    ]
