# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_gzh', '0002_gzh_info_gzh_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GZH_paper_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=100, unique=True)),
                ('gzh_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat_gzh.GZH_list')),
            ],
        ),
    ]
