# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_gzh', '0003_gzh_paper_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gzh_paper_list',
            name='paper_title',
            field=models.CharField(max_length=100),
        ),
    ]
