# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_gzh', '0005_auto_20160729_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='gzh',
            name='head_pic',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.CharField(max_length=30),
        ),
    ]
