# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_gzh', '0006_auto_20160729_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
